name             'masaki'
maintainer       'Masaki Matsushita'
maintainer_email 'glass.saga@gmail.com'
license          'All rights reserved'
description      'Set up my development environments'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.1.21'
depends          'homebrew'
depends          'sudo'
depends          'yum'
depends          'yum-epel'
depends          'apt'
depends          'git'
depends          'build-essential'
depends          'xml'
depends          'zlib'
depends          'readline'
depends          'ncurses'
depends          'sqlite'
depends          'mysql'
depends          'postgresql'
depends          'python'
depends          'erlang'
depends          'java'
depends          'perl'
depends          'php'
depends          'composer'
depends          'ssh_known_hosts'
depends          'zabbix'
depends          'jenkins'
depends          'lv'
depends          'ntp'
depends          'timezone-ii'
depends          'user'
